env:
  browser: true
  es6: true

parser: babel-eslint
plugins:
  - babel

parserOptions:
  # Support new ECMA syntax
  ecmaVersion: 2018
  ecmaFeatures:
    jsx: true
    modules: true
    spread: true
    restParams: true
  sourceType: module

# Using Airbnb style guide
extends:
  - react-app
  - eslint:recommended
  - airbnb
  - plugin:react/recommended
  - plugin:sonarjs/recommended
  - plugin:promise/recommended
  - plugin:lodash/recommended
  # Enables eslint-plugin-prettier and displays prettier errors as ESLint errors. Make sure this is always the last configuration in the extends array.
  - plugin:prettier/recommended

rules:
  # Custom
  arrow-parens: [2, 'as-needed']
  comma-dangle: ['error', 'only-multiline']
  no-console: ['error', { allow: ['log', 'warn', 'error'] }]

  react/jsx-props-no-spreading: [1, { custom: 'ignore' }]
  # Warning
  no-unused-vars: [1]

  # Disable
  lodash/prefer-lodash-method: [0]
  operator-linebreak: [0]
  implicit-arrow-linebreak: [0]
  dot-notation: [0]
  class-methods-use-this: [0]
  function-paren-newline: [0]
  import/prefer-default-export: [0]
  no-continue: [0]
  object-curly-newline: [0]
  react-hooks/exhaustive-deps: [0]
  react/jsx-wrap-multilines: [0]

settings:
  import/resolver:
    node:
      paths: ['src']
      extensions: ['.js', '.jsx', '.ts', '.tsx']
  react:
    createClass: createReactClass
    pragma: React
    version: detect
  propWrapperFunctions:
    - forbidExtraProps

globals:
  it: true
